package jtrrntzip;

public enum ZipReturn
{
	ZIPGOOD,
	ZIPFILELOCKED,
	ZIPFILECOUNTERROR,
	ZIPSIGNATUREERROR,
	ZIPEXTRADATAONENDOFZIP,
	ZIPUNSUPPORTEDCOMPRESSION,
	ZIPLOCALFILEHEADERERROR,
	ZIPCENTRALDIRERROR,
	ZIPENDOFCENTRALDIRECTORYERROR,
	ZIP64ENDOFCENTRALDIRERROR,
	ZIP64ENDOFCENTRALDIRECTORYLOCATORERROR,
	ZIPREADINGFROMOUTPUTFILE,
	ZIPWRITINGTOINPUTFILE,
	ZIPERRORGETTINGDATASTREAM,
	ZIPCRCDECODEERROR,
	ZIPDECODEERROR,
	ZIPFILENAMETOLONG,
	ZIPFILEALREADYOPEN,
	ZIPCANNOTFASTOPEN,
	ZIPERROROPENINGFILE,
	ZIPERRORFILENOTFOUND,
	ZIPERRORREADINGFILE,
	ZIPERRORTIMESTAMP,
	ZIPERRORROLLBACKFILE,
	ZIPTRYINGTOACCESSADIRECTORY,
	ZIPUNTESTED
}
